config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'

  resources :posts do
    resources :comments, module: :posts
  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }
  resources :users, only: [:show]
  root to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: "Comment"

  def comments
    Comment.where(commentable: commentable, parent_id: id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_comment, only: %i[ :destroy ]

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @commentable
    else
      redirect_to @commentable, alert: "Something went wrong"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(@commentable), status: :see_other, notice: "comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # def set_comment
    #   @comment = Comment.find(params[:id])
    # end

    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      # debugger
      @commentable = Post.find(params[:post_id])
    end
end

app/views/comments/_comment.html.erb
<div class="border-start ps-4 mb-4 mt-2">
  <span class="small">
    <%= link_to comment.user.first_name, user_path(comment.user) %> posted
  </span>
  <%= simple_format comment.body %>

  <div data-controller="reply">
    <%= link_to "Reply", "#", class: "small", data: { action: "click->reply#toggle" } %> |
    <%= link_to "Destroy", post_comment_path(comment.commentable, comment), class: "small", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <%= render partial: "comments/form", locals: { commentable: comment.commentable, parent_id: comment.id, class: "d-none", target: "reply.form" } %>
  </div>

  <%= render comment.comments %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [commentable, Comment.new], local: true, html: { class: local_assigns[:class], data: { target: local_assigns[:target] } } do |form| %>
  <div class="form-group">
    <%= form.text_area :body, placeholder: "Add a comment", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :parent_id, value: local_assigns[:parent_id] %>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>