config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'

  resources :posts do
    resources :comments, module: :posts
  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations" }
  resources :users, only: [:show]
  root to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private
    def set_commentable
      # debugger
      @commentable = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
      <%= form.text_area :body, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if post.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', post, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if post.persisted? %>
      <%= link_to "Cancel", post, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", posts_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Posts</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    Add New Post
  <% end %>
  </div>
</div>

<div class="table-responsive">

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>User</th>
        <th>Body</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <%= content_tag :tr, id: dom_id(post), class: dom_class(post) do %>
          <td><%= link_to post.title, post %></td>
          <td><%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user) %></td>
          <td><%= post.body %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="row page-header">
  <div class="col-md-3">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to posts_path, class: 'btn btn-sm btn-secondary' do %>
        All Posts
      <% end %>
      <% if @post.user == current_user %>
        <%= link_to edit_post_path(@post), class: 'btn btn-sm btn-primary' do %>
          Edit
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="card m-2">
  <div class="card-body">
    <h1 class="card-title"><%= @post.title %></h1>
    <div class="card-subtitle small mb-2 text-muted">By <%= link_to @post.user.first_name, @post.user %></div>
    <div class="card-text mb-2"><%= @post.body %></div>
    <div data-controller="reply">
      <%= link_to "Reply", "#", class: "card-link", data: { action: "click->reply#toggle" } %>
      <%= render partial: "comments/form", locals: { commentable: @post , class: "d-none", target: "reply.form" } %>
    </div>
  </div>
</div>

<section id="comments" class="m-2">
  <h3>Comments</h3>
  <%= render @post.comments.where(parent_id: nil) %>
</section>